apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DB_USER: "shopsphere_admin"
  DB_PASSWORD: "5H3aa77A3xV]lXP-4|*Ikk33lKH8"
  JWT_SECRET: "fcqOXIwMMwYixIDckRsLFoJAUxJgXY"
