apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DB_USER: "shopsphere_admin"
  DB_PASSWORD: "Uq3U7S*4T~[uTNjMPsYS(KJV-Ud)"
  JWT_SECRET: "fcqOXIwMMwYixIDckRsLFoJAUxJgXY"
