apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    type: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      labels:
        type: backend
    spec:
      containers:
      - name: shopsphere-backend
        image: umarayaz96/shopsphere-backend:42c01bc0b6dab29dc28c991f859f53412ad01acd
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: backend-configmap
        - secretRef:
            name: backend-secret
